export const APIErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',

  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',

  RATE_LIMITED: 'RATE_LIMITED',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  CONFLICT: 'CONFLICT',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  TIMEOUT: 'TIMEOUT',

  INVALID_API_KEY: 'INVALID_API_KEY',

  API_KEY_EXPIRED: 'API_KEY_EXPIRED',

  API_KEY_REVOKED: 'API_KEY_REVOKED',
} as const;

export type APIErrorCode = (typeof APIErrorCodes)[keyof typeof APIErrorCodes];
